services:
  - type: web
    name: maps-scraper
    env: docker  # <-- এখানে python এর বদলে docker দেওয়া হয়েছে
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: scraper-db
          property: connectionString

databases:
  - name: scraper-db
    plan: free
