services:
  - type: web
    name: maps-scraper-ai
    env: docker  # <-- এখানে python এর বদলে docker দেওয়া হয়েছে, এটাই ম্যাজিক!
    envVars:
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: scraper-db
    plan: free
